post:
  tags:
    - Products
  summary: Create product
  description: Requires ADMIN or USER.
  security:
    - bearerAuth: [ ]
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/product.yaml'
  responses:
    '200':
      description: Product created successfully
      content:
        application/json:
          schema:
            $ref: '../../schemas/product.yaml'
    '401':
      description: Unauthorized
    '403':
      description: Forbidden